# Generated by Django 5.2.6 on 2025-09-11 07:11

from django.db import migrations

def set_default_phone(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(phone__isnull=True).update(phone='Unknown')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(set_default_phone),
    ]
