# Generated by Django 5.2.6 on 2025-12-18 10:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Consulting', 'Consulting'), ('Nonprofit', 'Nonprofit'), ('Other', 'Other')], default='IT', max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('501+', '500+ Employees')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hiring_status', models.CharField(blank=True, choices=[('hiring', 'Hiring'), ('not_hiring', 'Not Hiring'), ('paused', 'Hiring Paused')], max_length=20, null=True)),
                ('remote_option', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], max_length=20, null=True)),
                ('benefits_offered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('healthcare', 'Healthcare'), ('paid_time_off', 'Paid Time Off'), ('retirement_plan', 'Retirement Plan'), ('stock_options', 'Stock Options'), ('gym_membership', 'Gym Membership'), ('child_care', 'Child Care'), ('paid_parents_leave', 'Paid Parental Leave'), ('other', 'Other')], max_length=50), blank=True, default=list, size=None)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('tax_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('registration_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('legal_status', models.CharField(choices=[('LLC', 'Limited Liability Company'), ('Corporation', 'Corporation'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Nonprofit', 'Nonprofit'), ('Other', 'Other')], default='LLC', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('document_type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('other', 'Other'), ('privacy', 'Privacy')], default='terms_and_conditions', max_length=100)),
                ('document', models.FileField(upload_to='company_documents/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company')),
            ],
        ),
    ]
