# Generated by Django 5.2.6 on 2025-09-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_benefits_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='benefits_offered',
            new_name='benefits_offer',
        ),
    ]
