# Generated by Django 5.2.6 on 2025-09-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_benefits_offered_company_benefits_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='benefits_offer',
            new_name='benefits_offered',
        ),
    ]
