# Generated by Django 5.2.6 on 2025-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_benefits_offer_company_benefits_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
