# Generated by Django 5.2.6 on 2025-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
